
export const data = [
  {
    id: 1,
    titleName: "Background Extend",
    beforeImage: "https://i.ibb.co/5mPFQKH/Background-Extend-Before.jpg",
    afterImage: "https://i.ibb.co/8n70YCCg/Background-Extend-After.jpg",
    btn: "View Details",
    info: "Background extension is the art of increasing the image canvas without compromising quality. It is essential when the original composition is too tight or needs to fit into specific formats. Our experts ensure the extended part looks natural and seamless. Whether it’s a studio shoot, product image, or model photo, the extended background matches lighting, shadows, and textures. We use advanced tools and manual techniques for precision. This service is often used for banners, posters, or ad materials. Clients can request any side of the photo to be extended — top, bottom, left, or right. We can replicate plain, textured, or patterned backgrounds based on your needs. This allows flexibility for cropping or placing text in designs. It is ideal for eCommerce, real estate, fashion, and product photography. With our background extend service, no image looks incomplete. Let your photos breathe with space, balance, and visual appeal.",
  },
  {
    id: 2,
    titleName: "Newborn",
    beforeImage: "https://i.ibb.co/N2P7XdN8/New-Bron-Before.jpg",
    afterImage: "https://i.ibb.co/HpNXwvfm/New-Bron-After.jpg",
    btn: "View Details",
    info: "Newborn editing requires a soft, careful touch and an eye for detail. We gently remove blemishes, flakes, and redness from a baby’s sensitive skin. Our edits maintain natural skin textures while enhancing tone and softness. Props like blankets, hats, or baskets are also cleaned and balanced. We brighten eyes without overexposing the face. Soft light and pastel tones are enhanced to create a dreamy feel. Background clutter is removed for a clean and pure look. Shadows are smoothed to ensure the baby remains the focus. Wrinkles in clothing or fabric are edited with care. Our goal is to keep the innocence and warmth intact. We avoid over-editing to protect realism. Every baby deserves a timeless and beautiful photo.",
  },
  {
    id: 3,
    titleName: "Maternity",
    beforeImage: "https://i.ibb.co/LDyZRw6b/Meternity-Before.jpg",
    afterImage: "https://i.ibb.co/Ngpk3t62/Meternity-After.jpg",
    btn: "View Details",
    info: "Maternity photos celebrate the miracle of motherhood. We enhance these images with elegance, warmth, and grace. Our editing focuses on smooth skin tones, glowing complexion, and subtle enhancements. Background distractions are removed to draw attention to the mother-to-be. We adjust contrast and brightness to evoke emotion and softness. Stretch marks and minor imperfections are softened but never erased entirely — to preserve authenticity. Garments and drapery are refined for a polished look. Light play and vignette effects may be added for dramatic depth. Hair flyaways, jewelry shine, and fabric wrinkles are adjusted as needed. We can also stylize maternity photos in a vintage, modern, or dreamy tone. The result is a powerful, feminine, and beautiful visual. Every photo tells a story of strength, love, and expectation.",
  },
  {
    id: 4,
    titleName: "Birthday",
    beforeImage: "https://i.ibb.co/JWcyZmH0/Birthday-Before.jpg",
    afterImage: "https://i.ibb.co/Z66H1TXK/Birthday-After.jpg",
    btn: "View Details",
    info: "Birthday photos are all about joy, color, and emotion. We enhance the brightness and contrast to bring out vivid tones. Background elements like decorations or guests can be cleaned up if cluttered. Our retouching smooths skin naturally and corrects lighting flaws. Balloons, cakes, and candles are made to pop visually. We fix red-eye, color cast, and any harsh shadows. Confetti and lights can be enhanced or added for a more festive look. Group photos are edited so everyone looks their best. Close-up shots are polished while keeping genuine smiles intact. We also offer light graphics or text overlays like “Happy Birthday.” Our edits maintain the playful energy of the event. Whether it's a child’s party or an adult celebration, your moments will shine. Every birthday becomes a timeless memory.",
  },
  {
    id: 5,
    titleName: "Wedding",
    beforeImage: "https://i.ibb.co/XrC4Yrs6/Wedding-Before.jpg",
    afterImage: "https://i.ibb.co/qFFY5BDf/Wedding-After.jpg",
    btn: "View Details",
    info: "Wedding photos are emotional, timeless, and priceless. Our editing enhances those precious moments with grace and elegance. We color-correct every photo to reflect the right warmth and ambiance. The bride and groom’s skin tones are balanced naturally. Background distractions like wires, people, or clutter are carefully removed. We enhance the details in dresses, jewelry, and floral arrangements. The lighting and shadows are adjusted to create depth and mood. For group photos, we correct alignment and ensure everyone looks their best. Photo retouching includes blemish removal, teeth whitening, and smoothing without making faces look plastic. We also apply cinematic tones for a romantic feel if desired. Black & white or vintage effects can be added selectively. Our wedding edits ensure timeless storytelling. Every frame becomes a memory to cherish forever.",
  },
  {
    id: 6,
    titleName: "Headshot",
    beforeImage: "https://i.ibb.co/HDCW4Z7q/1751781200957.jpg",
    afterImage: "https://i.ibb.co/fzcw8JWD/1751781200968.jpg",
    btn: "View Details",
    info: "Headshots require a polished, professional appearance. We remove blemishes and smooth skin while keeping natural detail. Hair is cleaned up and flyaways are removed for a tidy finish. Backgrounds can be blurred, cleaned, or changed to studio style. We whiten teeth, enhance eyes, and adjust jawlines subtly. Lighting correction brings balance and clarity to facial features. Clothing wrinkles and dust spots are also fixed. We retain texture so your image doesn’t look fake or plastic. Ideal for resumes, LinkedIn, corporate use, or personal branding. Each headshot is reviewed carefully for accuracy. We also adjust cropping and framing as needed. A professional headshot makes a strong first impression.",
  },
  {
    id: 7,
    titleName: "Family Photo",
    beforeImage: "https://i.ibb.co/Fcsrt9c/1751781201061.jpg",
    afterImage: "https://i.ibb.co/RTvPMt2f/1751781201048.jpg",
    btn: "View Details",
    info: "Family photos are about warmth, love, and harmony. Our editing ensures everyone looks their best in a single frame. We balance lighting so no face is over or under-exposed. Skin tones are unified, and blemishes or marks are gently retouched. We remove distractions like background clutter or objects. Clothing color corrections and smoothing are also included. Group alignment and posture corrections are done if possible. We enhance smiles and facial expressions without exaggeration. If someone blinked or had red eyes, we can fix that too. Old family photos can also be restored and modernized. Our edits maintain authenticity while adding visual charm. The final result is a treasured memory to frame and share.",
  },
  {
    id: 8,
    titleName: "Beauty Retouching",
    beforeImage: "https://i.ibb.co/hxB2TzLK/1751821315530.jpg",
    afterImage: "https://i.ibb.co/gbb25XBb/1751821315525.jpg",
    btn: "View Details",
    info: "This service is perfect for fashion, portrait, or model photography. We smooth skin, remove blemishes, and even out skin tone professionally. Eyes, lips, and eyebrows are enhanced for a sharp and attractive look. Hair is cleaned, shaped, and given natural shine. We adjust lighting and exposure for a high-end studio feel. Color grading is applied based on style — matte, warm, or cool. Background cleanup ensures full focus on the model. Clothing and accessories are polished for branding purposes. Teeth whitening and facial sculpting can be applied subtly. We maintain a balance between real and ideal. Retouching is done manually to ensure pixel-perfect quality. Your image will look glamorous, clean, and editorial-ready.",
  },
  {
    id: 9,
    titleName: "High End",
    beforeImage: "before.jpg",
    afterImage: "after.jpg",
    btn: "View Details",
    info: "High-end retouching is suitable for magazines, billboards, and luxury ads. It involves deep editing with pixel-level detail and precision. Every skin pore is refined without losing texture. Shadows and highlights are perfectly balanced for drama and depth. Hair is shaped and enhanced with natural volume and light. Advanced dodging and burning are applied to contour the face. We remove all distractions from the background. Garments are cleaned, adjusted, and sharpened. Color tones are matched to the brand’s identity. Every element is aligned, straightened, and sharpened. We use frequency separation, tone mapping, and skin separation. This is the most premium level of photo enhancement.",
  },
  {
    id: 10,
    titleName: "Galaree Remove",
    beforeImage: "https://i.ibb.co/3mC3q3tX/1751781201039.jpg",
    afterImage: "https://i.ibb.co/j9WvHht6/1751781201031.jpg",
    btn: "View Details",
    info: "Managing large photo galleries can be overwhelming. We help clean, organize, and filter image galleries. Duplicate, blurry, or unwanted photos are identified and removed. Clients receive only the best versions for display or storage. Cropping and alignment corrections are also applied. We enhance selected photos for color and lighting. File renaming and resizing can be added upon request. This is ideal for wedding, event, or fashion photographers. You can focus on shooting while we manage the cleanup. Consistency is maintained across the entire gallery. Each chosen photo gets the editing it deserves. Your final gallery will be professional and presentation-ready.",
  },
  {
    id: 11,
    titleName: "Bridal Boudoir",
    beforeImage: "before.jpg",
    afterImage: "after.jpg",
    btn: "View Details",
    info: "Bridal boudoir is intimate, elegant, and romantic. Our editing respects privacy while enhancing confidence. Skin is retouched smoothly while preserving softness. Lighting is adjusted for mood and sensuality. Backgrounds are cleaned for simplicity and elegance. Outfits, lingerie, and accessories are refined gently. We remove wrinkles in sheets or fabrics if needed. Hair is enhanced with natural volume and shine. Colors can be made warm, soft, or vintage. Every edit is tasteful and respectful of emotion. Your bridal boudoir photos will feel bold yet beautiful. A confident memory captured for a lifetime.",
  },
  // {
  //   id: 12,
  //   titleName: "Fashion and retouching",
  //   beforeImage: "before.jpg",
  //   afterImage: "after.jpg",
  //   btn: "View Details",
  // },
  {
    id: 13,
    titleName: "Clipping Path",
    beforeImage: "https://i.ibb.co/Dfb7jPDM/Clipping-Path-Bg-Change-Before.jpg",
    afterImage: "https://i.ibb.co/qMrp8zPG/Clipping-Path-Bg-Change-After.jpg",
    btn: "View Details",
    info: "Clipping path uses the pen tool to cut out objects precisely. We manually outline products to separate them from the background. Clean edges ensure perfect results with no halos or roughness. Ideal for catalogs, websites, or print designs. It supports background changes or transparent PNG exports. Complex shapes like jewelry or furniture are handled with care. Multiple paths can be created for different product parts. Our team avoids auto-selections for maximum quality. Zoomed-in work ensures pixel perfection. Shadows and reflection options can be added after clipping. Files are delivered in required formats and sizes. This is the base for all product editing.",
  },
  {
    id: 14,
    titleName: "Multi Path",
    beforeImage: "https://i.ibb.co/qFY8hGjK/1751781200864.jpg",
    afterImage: "https://i.ibb.co/CsmmmhpG/1751781200845.jpg",
    btn: "View Details",
    info: "Multi-path offers more control than simple clipping. Different parts of an image are clipped separately. This is useful for color correction or applying effects to specific areas. For example, editing only the shirt or shoe in a fashion photo. It also helps in re-coloring, shadow creation, or object swapping. Multi-path supports bulk editing of variations. We use advanced pen tool work for exact selection. Colors can be changed for multiple versions of the same product. Designers can control each path for creative use. This is essential for high-end eCommerce and fashion projects. We ensure every path is clean and named properly. Multi-path editing saves time and boosts flexibility.",
  },
  {
    id: 15,
    titleName: "Background Removal",
    beforeImage: "before.jpg",
    afterImage: "after.jpg",
    btn: "View Details",
    info: "We remove backgrounds with clean, sharp edges and accurate details. The subject remains untouched and natural. Whether it’s for white, transparent, or custom backgrounds — we’ve got you. Ideal for Amazon, Shopify, or catalog-ready images. Hair, fur, or complex objects are handled with care. We don’t rely solely on AI cutouts — manual checks are always done. Lighting and shadows are preserved where necessary. We ensure the product pops on any new background. This service boosts consistency across product lines. Delivery in PNG, JPG, or PSD as needed. You’ll receive print-ready and web-ready versions. Fast, clean, and accurate background removal guaranteed.",
  },
  {
    id: 16,
    titleName: "Alpha Masking",
    beforeImage: "https://i.ibb.co/h1LR2q6V/Alpha-Before.jpg",
    afterImage: "https://i.ibb.co/1YqQC7Lm/Alpha-After.jpg",
    btn: "View Details",
    info: "Alpha masking is great for semi-transparent or soft edges. It's ideal for hair, feathers, glass, or smoke. We use layer masking to control opacity and detail. This technique helps retain soft glow or blur effects. It also supports better background replacement. Unlike clipping paths, masking handles complexity better. We use it for fashion, portrait, and product photos. It works best on high-resolution images. Manual control ensures pixel accuracy. We clean the image without harming detail. Files are delivered with editable masks for your use. Alpha masking delivers a refined, natural finish.",
  },
  {
    id: 17,
    titleName: "Shadow Making",
    beforeImage: "https://i.ibb.co/5X1fC52d/1751781201143.jpg",
    afterImage: "https://i.ibb.co/HL6JRmPg/1751781201132.jpg",
    btn: "View Details",
    info: "Shadows add realism and depth to product photos. We create natural, drop, or reflection shadows as required. Products look more grounded and professional with shadows. Ideal for eCommerce, ad banners, and catalogs. Our shadow angles and softness match the lighting. We can replicate real shadows or create new ones. Shadows are added manually for authenticity. Light source direction is carefully studied. Drop shadows create separation from white backgrounds. Reflection shadows give a premium glossy effect. Soft shadows feel natural and smooth. Your images gain dimension and look visually appealing.",
  },
  {
    id: 18,
    titleName: "Ghost Mannequin",
    beforeImage: "https://i.ibb.co/whpjcfDF/1751781200992.jpg",
    afterImage: "https://i.ibb.co/TMNH1VP0/1751781200979.jpg",
    btn: "View Details",
    info: "Ghost mannequin editing removes mannequins while keeping clothing 3D. Perfect for shirts, jackets, and dresses in eCommerce. We combine multiple images (front, back, neck) into one. Hollow areas are filled to show the inside of garments. Wrinkles are fixed, and shape is restored. Backgrounds are made white or transparent. This creates a clean, professional product display. We keep clothing textures and stitching clear. Shadows are preserved or added for realism. Files are optimized for web or print. You’ll get a store-ready photo every time. Ghost mannequin improves conversions and product appeal.",
  },
  {
    id: 19,
    titleName: "Ree Color",
    beforeImage: "https://i.ibb.co/XxkvGKnG/1751781201179.jpg",
    afterImage: "https://i.ibb.co/hJrF2rnK/1751781201169.jpg",
    btn: "View Details",
    info: "Recoloring changes object colors without retaking photos. It's ideal for displaying product variations (like blue, red, or green). We retain texture while changing fabric or surface color. No loss of detail, shine, or realism. It's perfect for fashion, packaging, or furniture products. Colors can be matched with brand codes or samples. We can recolor single objects or bulk sets. Shadows, highlights, and gloss are preserved. This is faster and more cost-effective than reshooting. Backgrounds remain unaffected. Products get a new look with zero hassle. Visual consistency and speed — all in one.",
  },
  {
    id: 20,
    titleName: "Image Resize",
    beforeImage: "https://i.ibb.co/vvv276J7/1751781200916.jpg",
    afterImage: "https://i.ibb.co/jZrXYQ0k/1751781200927.jpg",
    btn: "View Details",
    info: "We resize images for any platform without losing quality. Social media, web, print — we know the right dimensions. Aspect ratio is preserved or cropped as needed. Pixel-perfect output is guaranteed. Resolution can be optimized for fast load times. Ideal for thumbnails, galleries, ads, or large prints. We can resize single files or entire folders. Naming and format customization is included. Watermark addition or removal is also available. We offer resizing in multiple formats (JPG, PNG, WEBP). The result: perfectly sized, sharp, and fast-loading images. A small change with big impact.",
  },
];

